import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 侧边栏信息架构：
 * - 入门指南 / 核心功能 / 场景教程 / 进阶使用：目录内自动生成，
 *   顺序由各文档 frontmatter 的 sidebar_position 控制
 * - 配置指南：guides/ 下四个子目录（转写引擎 / 云端听写 / 翻译服务 / 配音服务），
 *   子分类由各目录的 _category_.json 定义
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: '入门指南',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'intro' }],
    },
    {
      type: 'category',
      label: '核心功能',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'features' }],
    },
    {
      type: 'category',
      label: '配置指南',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: '场景教程',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'scenarios' }],
    },
    {
      type: 'category',
      label: '进阶使用',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'advanced' }],
    },
    {
      type: 'doc',
      id: 'faq',
      label: '常见问题',
    },
  ],
};

export default sidebars;
